- Gillian-JS/Examples/JaVerT/BST.js
- Gillian-JS/Examples/JaVerT/SLL.js
- Gillian-JS/lib/Parsing/Javert_Parser.mly
- Gillian-JS/lib/Test262/dune
- GillianCore/engine/Abstraction/Verifier.ml
> fix verification, fix coloring, remove unnecessary prints

- .github/workflows/Heavy.yml
- .github/workflows/light.yml
- Gillian-C/lib/sRunner.ml
This enables test262 + Collection-C + Buckets on push and PRs to master
> Enable long tests

- GillianCore/GIL_Parser/gil_parsing.ml
Refactor duplicate code into separate functions, reduce the size of
overlong comments and simplify some of the import-resolving logic. Add
the missing 'else' expression when the current import to be resolved
has been seen already.
> Refactor eprog_to_prog

- Gillian-C/examples/with-imports/concrete/test.c
- Gillian-C/includes/gillian-c.h
- Gillian-C/includes/stdlib.h
- Gillian-C/includes/string.h
- Gillian-C/lib/gil_logic_gen.ml
- Gillian-C/lib/gilgen.ml
- Gillian-C/lib/gilgen.mli
- Gillian-C/lib/parserAndCompiler.ml
- GillianCore/CommandLine/CommandLine.ml
These are the final changes needed to make all of the multi-file Collections-C tests pass.
> Correctly handle C static global variables and functions

- GillianCore/logging/logging.ml
- GillianCore/logging/logging.mli
- esy.json
- esy.lock/index.json
- esy.lock/opam/cinaps.v0.13.0/opam
- esy.lock/opam/lambda-term.3.0.0/opam
- esy.lock/opam/lwt.5.3.0/opam
- esy.lock/opam/mew.0.1.0/opam
- esy.lock/opam/mew_vi.0.3.0/opam
- esy.lock/opam/ppxfind.1.4/opam
- esy.lock/opam/trie.1.0.0/opam
- esy.lock/opam/utop.2.5.0/opam
- esy.lock/opam/zed.3.0.1/opam
Decorator for opening a new logging phase when executing a function and closing it after the function returns. Uses `ocaml-ppx/cinaps` to generate decorators for functions with a variable number of arguments.
> Logging: phase decorator

- .gitignore
> gitignore: ignore development container

- .gitignore
- esy.json
- githooks/clean.py
- githooks/common.py
fixes #20 and allows to clean hooks too
> Improve githooks situation

- GillianCore/engine/ConcreteSemantics/CExprEval.ml
Signed-off-by: Radu Lacraru <radu.lacraru97@gmail.com>
> Fix missing case from expression evaluation

- GillianCore/logging/databaseReporter.ml
- GillianCore/logging/default.ml
- GillianCore/logging/fileReporter.ml
- GillianCore/logging/logging.ml
- GillianCore/logging/logging.mli
- GillianCore/logging/report.ml
- GillianCore/logging/reportBuilder.ml
- GillianCore/logging/reporter.ml
Based on #45, will rebase after it gets merged.
> Logging: language dependent logging

- GillianCore/logging/reportBuilder.ml
Signed-off-by: Radu Lacraru <radu.lacraru97@gmail.com>
> Logging: fix bug introduced by phase equality

- GillianCore/logging/reportBuilder.ml
Signed-off-by: Radu Lacraru <radu.lacraru97@gmail.com>
> Logging: derive report title from content

- GillianCore/GIL_Syntax/Expr.ml
- GillianCore/GIL_Syntax/Gil_syntax.mli
- wisl/examples/DLL_recursive.wisl
- wisl/lib/ParserAndCompiler/WLexer.mll
- wisl/lib/ParserAndCompiler/WParser.mly
- wisl/lib/ParserAndCompiler/wisl2Gil.ml
- wisl/lib/semantics/constr.ml
- wisl/lib/semantics/dune
- wisl/lib/semantics/wislCMemory.ml
- wisl/lib/semantics/wislLActions.ml
- wisl/lib/semantics/wislLActions.mli
- wisl/lib/semantics/wislSHeap.ml
- wisl/lib/semantics/wislSHeap.mli
- wisl/lib/semantics/wislSMemory.ml
- wisl/lib/syntax/WLExpr.ml
- wisl/runtime/wisl_pointer_arith.gil
-> wisl memory model matches "simplfiied C memory model" from formalism
-> Several fixes in the compiler
> Reworked wisl memory model

- GillianCore/CommandLine/CommandLine.ml
- GillianCore/engine/Abstraction/UP.ml
- GillianCore/engine/Abstraction/Unifier.ml
- GillianCore/engine/Abstraction/Verifier.ml
- GillianCore/engine/FOLogic/Reduction.ml
- GillianCore/engine/GeneralSemantics/ESubst.ml
- wisl/examples/SLL/SLL_ex.wisl
- wisl/examples/SLL/SLL_ox.wisl
- wisl/examples/SLL/SLL_ux_error.wisl
- wisl/lib/ParserAndCompiler/WParser.mly
Under-approximating verification basics
> Under approx

- Gillian-C/runtime/stdlib_archi32.gil
- Gillian-C/runtime/stdlib_archi64.gil
it should check that the pointer is to 0 and should be nop on NULL
> fix the behaviour of free

- GillianCore/engine/GeneralSemantics/General/GInterpreter.ml
> better error message on action failure

- GillianCore/CommandLine/CommandLine.ml
- GillianCore/debugging/adapter/debugAdapter.ml
- GillianCore/debugging/debugger/debugger.ml
- GillianCore/debugging/lifter/GilLifter.ml
- debugger-vscode-extension/package.json
- debugger-vscode-extension/src/extension.ts
- debugger-vscode-extension/src/webviews/src/TreeMapView/NodeWrap.tsx
- wisl/lib/debugging/wislLifter.ml
Resolves #157
Resolves #154
~~Depends on #156 - merge that one first!~~
> Manual proof mode, WislLifter map insertion resilience, fix tooltips

- .github/workflows/ci.yml
- .gitignore
- Dockerfile
- _docs/README.md
- _docs/index.html
Automatically deploy docs to to the [GillianPlatform.github.io repo](https://github.com/GillianPlatform.github.io).
Also (hopefully) fixes Docker CI.
Resolves #142
Resolves #187
> Deploy docs

- GillianCore/GIL_Parser/gil_parsing.mli
- GillianCore/lib/gillian.ml
- GillianCore/utils/allocators_intf.ml
- GillianCore/utils/compare.ml
- GillianCore/utils/config.ml
- GillianCore/utils/containers.ml
- GillianCore/utils/exec_mode.ml
- GillianCore/utils/ext_list.mli
- GillianCore/utils/prelude.ml
- GillianCore/utils/syntaxes.ml
- GillianCore/utils/utils.ml
Also rejigs some module definitions in `Utils` because odoc is a mess.
> Document `Gil_parsing`

- GillianCore/GIL_Syntax/Lemma.ml
- GillianCore/gil_parser/GIL_Parser.mly
Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>
> Lemma names can be arbitrary

- GillianCore/GIL_Syntax/Asrt.ml
- GillianCore/GIL_Syntax/Expr.ml
- GillianCore/GIL_Syntax/Gil_syntax.mli
- GillianCore/GIL_Syntax/Visitors.ml
- GillianCore/engine/FOLogic/FOSolver.ml
- GillianCore/engine/FOLogic/FOSolver.mli
- GillianCore/monadic/FOSolver.ml
- wisl/lib/semantics/wislSHeap.ml
Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>
> check sat with only relevant information in monadic mode

- Gillian-C/examples/amazon/bugs/header.c
- Gillian-C/examples/amazon/ec.c
- Gillian-C/examples/amazon/header.c
- Gillian-C/examples/amazon/logic/ListLogic.gil
- Gillian-JS/Examples/Amazon/EncryptionHeaderLogic.gil
- Gillian-JS/Examples/Amazon/ListLogic.gil
- Gillian-JS/Examples/Amazon/bugs/frozen/AmazonLogic.jsil
- Gillian-JS/Examples/Amazon/bugs/frozen/ListLogic.gil
- Gillian-JS/Examples/Amazon/bugs/frozen/deserialize_factory.js
- Gillian-JS/Examples/Amazon/bugs/pp/AmazonLogic.jsil
- Gillian-JS/Examples/Amazon/bugs/pp/ListLogic.gil
- Gillian-JS/Examples/Amazon/bugs/pp/deserialize_factory.js
- Gillian-JS/Examples/Amazon/deserialize_factory.js
- GillianCore/engine/Abstraction/Unifier.ml
- debugger-vscode-extension/sampleWorkspace/c/amazon/logic/ListLogic.gil
> Flip arguments to `bind` when unfolding

- .github/workflows/ci.yml
- Gillian-C/examples/symbolic/bug_examples/array_oob.c
- Gillian-C/examples/symbolic/globalvar.c
- Gillian-C/examples/symbolic/unstructured.c
- Gillian-C/examples/verification/array.c
- Gillian-C/includes/gillian-c.h
- Gillian-C/lib/MonadicSMemory.ml
- Gillian-C/lib/SHeapTree.ml
- Gillian-C/lib/SHeapTree.mli
- Gillian-C/lib/cConstants.ml
- Gillian-C/lib/cParserAndCompiler.ml
- Gillian-C/lib/config.ml
- Gillian-C/lib/config_compcert.ml
- Gillian-C/lib/gilgen.ml
- Gillian-C/runtime/binops_common.gil
- Gillian-JS/lib/Compiler/JS2JSIL_Compiler.ml
- Gillian-JS/lib/Compiler/JSIL2GIL.ml
- Gillian-JS/runtime/JSLogic/bi_javert_predicates.jsil
- GillianCore/command_line/s_interpreter_console.ml
- GillianCore/engine/Abstraction/MP.ml
- GillianCore/engine/Abstraction/Verifier.ml
- GillianCore/engine/BiAbduction/BiState.ml
- GillianCore/engine/concrete_semantics/CState.ml
- GillianCore/engine/general_semantics/general/exec_err.ml
- GillianCore/engine/general_semantics/general/g_interpreter.ml
- GillianCore/engine/general_semantics/general/g_interpreter_intf.ml
- GillianCore/engine/general_semantics/state.ml
- GillianCore/incrementalAnalysis/resultsDir.ml
- GillianCore/utils/command_line_utils.ml
- GillianCore/utils/config.ml
> Gillian c things for thesis

- GillianCore/GIL_Syntax/Expr.ml
- GillianCore/GIL_Syntax/Formula.ml
- GillianCore/GIL_Syntax/Gil_syntax.mli
- GillianCore/GIL_Syntax/TypeDef__.ml
- GillianCore/engine/Abstraction/MP.ml
- GillianCore/engine/Abstraction/Normaliser.ml
- GillianCore/engine/FOLogic/Reduction.ml
- GillianCore/engine/FOLogic/typing.ml
- GillianCore/engine/concrete_semantics/CExprEval.ml
- GillianCore/engine/general_semantics/eSubst.ml
- GillianCore/engine/symbolic_semantics/SState.ml
- GillianCore/gil_parser/GIL_Parser.mly
- GillianCore/z3/z3_encoding.ml
- **add EForall to expression AST**
- **Don't crash when reducing || or && and one of the sides can't be reduced.**
> forall exprs

- GillianCore/monadic/delayed.ml
- GillianCore/monadic/delayed.mli
Allow branching without modifying the PC
> Add `Delayed.branches`

- GillianCore/engine/Abstraction/Matcher.ml
- GillianCore/engine/Abstraction/Matcher.mli
- GillianCore/engine/Abstraction/PState.ml
- GillianCore/engine/Abstraction/PState.mli
- GillianCore/engine/Abstraction/Verifier.ml
- GillianCore/engine/BiAbduction/BiState.ml
- GillianCore/engine/concrete_semantics/CState.ml
- GillianCore/engine/general_semantics/state.ml
- GillianCore/engine/symbolic_semantics/SState.ml
- GillianCore/gil_parser/GIL_Parser.mly
- dune-project
- gillian.opam
- wisl/lib/ParserAndCompiler/WParser.mly
It's currently unused and should be done better anyway
> Remove all notions of variants from the Gillian engine
